--1.Liệt kê DS khách hàng (TênKH, DC) có đặt hàng vào Ngày tháng năm X.
--2.Liệt kê DS khách hàng (TênKH, DC) có đặt hàng sản phẩm có mã số X.
--3.Liệt kê DS khách hàng (TênKH, DC) có đặt hàng với tổng số tiền trên X (1 đơn).
--4.Liệt kê DS khách hàng (TênKH, DC) có đặt hàng với tổng số tiền trên X (tất cả).
--5.Liệt kê DS sản phẩm (TênSP, Giá thành SX, Giá) bán lãi trên X.
--6.Liệt kê DS khách hàng (TênKH, DC) đã trên X ngày rồi chưa đặt hàng.
--7.Liệt kê DS sản phẩm (TênSP, Số đơn) có tổng số đơn đặt hàng trên X.
--8.Liệt kê DS sản phẩm (TênSP, Tổng SL) có tổng số lượng đặt hàng trên X.
--9.Liệt kê DS sản phẩm (TênSP, Tổng số tiền) có tổng số tiền đặt hàng trên X.
