--1 .bak file
--2 .mdf va .log file
--3 .sql file

--BACK UP
BACKUP DATABASE QLBANHANG2
TO DISK = 'D:\sql\qlBanHang.bak'
WITH PASSWORD = '123'
--RESTORE
RESTORE DATABASE QLBANHANG2
FROM DISK = 'D:\sql\qlBanHang.bak'
WITH PASSWORD = '123'

--DETACH
SP_DETACH_DB QLBANHANG2
--ATTACH
CREATE DATABASE QLBANHANG2
ON (FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVER2019\MSSQL\DATA\QLBANHANG2.mdf')
FOR ATTACH

--FILE SCRIPT .sql

--Create db and set location for .mdf file and .log file
CREATE DATABASE QLBANHANG2
 ON
( NAME = N'QLBANHANG2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVER2019\MSSQL\DATA\QLBANHANG2.mdf')
 LOG ON 
( NAME = N'QLBANHANG2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVER2019\MSSQL\DATA\QLBANHANG2_log.ldf')
GO