DECLARE @var1 NVARCHAR(20)
SET @var1 = 'Demo'
SELECT @var1 AS TEST

CREATE DATABASE
DROP DATABASE

--doi ten db
EXEC sp_renamedb 'DB01', 'DB02'

--Kiem tra cac constraint tren 1 table
sp_helpconstraINT 'DONHANG'

DROP TABLE IF EXISTS MYTABLE

--tao bang va khoa chinh
CREATE TABLE HEDT(
    MAHE CHAR(2) NOT NULL CONSTRAINT PK_MAHE PRIMARY KEY,
    TENHE VARCHAR(15) NOT NULL,
    HPCB INT NOT NULL
)

--IDENTITY
CREATE TABLE TEMP2(
	MaKhoa INT IDENTITY(1,1),
	Ngay DATE
)

--tao khoa ngoai
ALTER TABLE DSLOP ADD
    CONSTRAINT FK_MAHE FOREIGN KEY (MAHE) REFERENCES HEDT(MAHE)

--vai rang buoc co ban
ALTER TABLE DSLOP ADD
    CONSTRAINT UQ_TENLOP UNIQUE(TENLOP) --du lieu la duy nhat
ALTER TABLE HEDT ADD
    CONSTRAINT CK_HPCB CHECK (HPCB>=1500000) --rang buoc ve gia tri
ALTER TABLE DSSV ADD
    CONSTRAINT CK_DIENUT CHECK (DIENUT IN ('KHONG', 'CO')) --du lieu chi chap nhan 2 gia tri

--N truoc kieu du lieu NVARCHAR
ALTER TABLE SANPHAM ADD
	CONSTRAINT CK_DONVI CHECK (DonVi IN(N'thùng', N'chai', N'túi', N'hộp', N'con', N'lốc', N'kg', N'gói', N'cân'))

ALTER TABLE NHANVIEN ADD
    CONSTRAINT CK_NGAYSINH CHECK (NgaySinh<getDATE()) --ham getDATE() tra ve ngay thang hien tai
ALTER TABLE DONHANG ADD
    CONSTRAINT CK_NGAYDATHANG CHECK (NgayDatHang>=getDATE())
ALTER TABLE KHOA2 ADD
	CONSTRAINT DF_SOCBGD2 DEFAULT 1 FOR SoCBGD --tao gia tri mac dinh 1

--cau lenh INSERT
INSERT INTO DSSV
VALUES
    ('S0001', 'NGUYEN THANH NHAN', '7/1/1990', '08CD01', 'KHONG'),
    ('S0002', 'NGUYEN THI THANH', '5/25/1991', '08CD02', 'CO'),
    ('S0003', 'TRAN NGUYEN', '4/12/1993', '08TC02', 'KHONG'),

--cau lenh DELETE
DELETE FROM dbo.CUNGCAP
WHERE CungCapID BETWEEN 4 AND 6;

--cau lenh UPDATE
UPDATE dbo.NHANVIEN
SET GhiChu = N'Làm thời vụ'
WHERE NhanVienID IN (3, 5, 7);

--cau lenh SELECT co ban

SELECT MASV, HOTEN, TENLOP
FROM DSSV, DSLOP
WHERE DSSV.MALOP=DSLOP.MALOP
	AND MAHE='CD'
--subquery
SELECT TENHE
FROM HEDT
WHERE HPCB = (SELECT MAX(HPCB) FROM HEDT)
--GROUP BY
SELECT MALOP, COUNT(MASV) AS [SOSV]
FROM DSSV
GROUP BY MALOP
--4.5
SELECT MALOP, TENLOP
FROM DSLOP
WHERE MALOP NOT IN (SELECT MALOP FROM DSSV)

--cau lenh VIEW
-- syntax
/*
CREATE VIEW Ten_View
AS
	Cau lenh truy van
*/
--7.1
CREATE VIEW XEMSODONTHEOTHANG
AS
	SELECT MONTH(NgayDatHang) AS [Thang], COUNT(*) AS [Tong don hang]
	FROM DONHANG
	GROUP BY MONTH(NgayDatHang)
GO
--7.2
CREATE VIEW SOLUONGKHTHEOTP
AS
	SELECT ThanhPho, COUNT(*) AS [So luong KH]
	FROM KHACHHANG
	GROUP BY ThanhPho
GO
--7.4
CREATE VIEW SPBANNHIEUNHAT
AS
	SELECT TenSanPham, SUM(SoLuong) AS [Tong so luong ban]
	FROM SANPHAM AS SP, DONHANGCHITIET AS DHCT
	WHERE SP.SanPhamID=DHCT.SanPhamID
	GROUP BY SP.SanPhamID, TenSanPham
	ORDER BY Sum(SoLuong) DESC
GO
SELECT TenSanPham
FROM SANPHAM
WHERE SanPhamID =
(
	SELECT SanPhamID
	FROM TONGSLTHEOIDPS
	WHERE TongSL = (SELECT MAX(TongSL) FROM TONGSLTHEOIDPS)
)
GO
--CO SUA
CREATE VIEW TONGSLTHEOIDPS
AS
	SELECT SanPhamID, sum(SoLuong) AS TongSL
	FROM DONHANGCHITIET
	GROUP BY SanPhamID
GO
CREATE VIEW SANPHAMBANMAX
AS
	SELECT TenSanPham
	FROM TONGSLTHEOIDPS T, SANPHAM P
	WHERE TongSL = (SELECT MAX(TongSL) FROM TONGSLTHEOIDPS)
		AND T.SanPhamID=P.SanPhamID
GO
